# Generated by Django 4.1 on 2022-11-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barrio', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('Generos', models.CharField(blank=True, choices=[('Femenino', 'Mujer'), ('Masculino', 'Hombre'), ('Otro', 'Otro')], default='Femenino', max_length=20, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('telefono_emergencia', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('red_social', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato_1', models.CharField(max_length=20)),
                ('dato_2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('modo_de_pago', models.CharField(max_length=20)),
                ('plan', models.CharField(max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('dias_de_entrenamiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salud_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_1', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3)),
                ('pregunta_2', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3)),
                ('pregunta_3', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTec_model',
            fields=[
                ('clientes_model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='STARKE_APP.clientes_model')),
                ('peso', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('pregunta_1', models.CharField(blank=True, max_length=50, null=True)),
                ('pregunta_2', models.CharField(blank=True, max_length=50, null=True)),
                ('pregunta_3', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('STARKE_APP.clientes_model',),
        ),
        migrations.CreateModel(
            name='model2',
            fields=[
                ('model1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='STARKE_APP.model1')),
                ('dato_3', models.CharField(max_length=20)),
                ('dato_4', models.CharField(max_length=20)),
            ],
            bases=('STARKE_APP.model1',),
        ),
        migrations.CreateModel(
            name='model34',
            fields=[
                ('model1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='STARKE_APP.model1')),
                ('dato_5', models.CharField(max_length=20)),
                ('dato_6', models.CharField(max_length=20)),
            ],
            bases=('STARKE_APP.model1',),
        ),
    ]
