# Generated by Django 4.1 on 2022-12-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARKE_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model2',
            name='model1_ptr',
        ),
        migrations.RemoveField(
            model_name='model34',
            name='model1_ptr',
        ),
        migrations.DeleteModel(
            name='model1',
        ),
        migrations.DeleteModel(
            name='model2',
        ),
        migrations.DeleteModel(
            name='model34',
        ),
    ]
