# Generated by Django 4.1 on 2022-09-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARKE_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
