# Generated by Django 4.1 on 2022-10-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARKE_APP', '0002_persona_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField()),
                ('Generos', models.CharField(choices=[('Femenino', 'Mujer'), ('Masculino', 'Hombre'), ('Otro', 'Otro')], default='Femenino', max_length=20)),
                ('telefono', models.IntegerField()),
                ('telefono_emergencia', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('red_social', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Persona_2',
        ),
    ]
