# Generated by Django 4.1 on 2022-10-31 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STARKE_APP', '0004_remove_clientes_model_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes_model',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.CreateModel(
            name='FichaTec_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alura', models.FloatField()),
                ('pregunta_1', models.CharField(max_length=50)),
                ('pregunta_2', models.CharField(max_length=50)),
                ('pregunta_3', models.CharField(max_length=50)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STARKE_APP.clientes_model')),
            ],
        ),
    ]
