# Generated by Django 4.1 on 2022-10-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARKE_APP', '0005_alter_clientes_model_email_fichatec_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatec_model',
            name='alura',
        ),
        migrations.AddField(
            model_name='fichatec_model',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichatec_model',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichatec_model',
            name='pregunta_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichatec_model',
            name='pregunta_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichatec_model',
            name='pregunta_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
