# Generated by Django 4.1 on 2022-11-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARKE_APP', '0006_remove_fichatec_model_alura_fichatec_model_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes_model',
            name='fecha_nac',
            field=models.DateTimeField(blank=True, null=True, verbose_name='%d/%m/%Y'),
        ),
    ]
