# Generated by Django 4.1 on 2022-11-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARKE_APP', '0010_alter_clientes_model_fecha_nac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagis_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('modo_de_pago', models.CharField(max_length=20)),
                ('plan', models.CharField(max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('dias_de_entrenamiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salud_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_1', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3)),
                ('pregunta_2', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3)),
                ('pregunta_3', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='clientes_model',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
    ]
