# Generated by Django 4.1 on 2022-11-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARKE_APP', '0011_pagis_model_salud_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatec_model',
            name='owner',
            field=models.IntegerField(blank=True, default=1, verbose_name='Dueño datos'),
        ),
    ]
