# Generated by Django 4.1 on 2022-11-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARKE_APP', '0012_fichatec_model_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
