# Generated by Django 4.1 on 2022-11-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARKE_APP', '0013_alter_clientes_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes_model',
            name='dni',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fichatec_model',
            name='dni',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
