# Generated by Django 4.1 on 2022-11-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARKE_APP', '0014_clientes_model_dni_fichatec_model_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes_model',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichatec_model',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
